### ISSUE TITLE
可以发私信吗？

### ISSUE THREAD

**Issue by charujing** [hmgle/send_wave#2]
谢谢

**Comment by hmgle** [comment]
当时没有发私信的需求，不支持。

**Comment by charujing** [comment]
> 当时没有发私信的需求，不支持。

非常感谢回复。请问有什么资料推荐下吗？我想写个发私信的包。

**Comment by hmgle** [comment]
> > 当时没有发私信的需求，不支持。
> 
> 非常感谢回复。请问有什么资料推荐下吗？我想写个发私信的包。

看官方 API 文档就可以了。
以饭否为例，根据发送消息的 [API](https://github.com/FanfouAPI/FanFouAPIDoc/wiki/statuses.update)，在发送饭否消息的[代码](https://github.com/hmgle/send_wave/blob/aa06c7cd524935ddf9f2ef1e971fedafe1d6bc9c/fanfou.py#L18) 加上 `in_reply_to_user_id` 参数就好了。
